### ISSUE TITLE
Error when running dask without sidecar

### ISSUE THREAD

**Issue by mat-adamec** [CoffeaTeam/coffea-casa#79] opened 2021-02-17 19:59 UTC
Occasionally, when I run without the sidecar, I see a never-ending list of this strange KeyError:

![image](https://user-images.githubusercontent.com/25493839/108260515-074c3f00-7128-11eb-9632-f36c8a4df5e7.png)

This happens especially when I restart my kernel in the middle of a run on analysis-casa.ipynb - something which probably shouldn't be done, but still feels reportable as an error. It seems to run fine on another restart, and so a temporary solution is just to re-run it again.

**Comment by oshadura** [comment] 2021-04-22 14:37
Closing as a duplicate of https://github.com/CoffeaTeam/coffea-casa/issues/79

**Closed by oshadura** 2021-04-22 14:38 UTC
Labels: bug
