### ISSUE TITLE
Errors and warnings while making benchmarks

### ISSUE THREAD

**Issue by mat-adamec** [CoffeaTeam/coffea-casa#43] opened 2020-10-26 19:02 UTC
I spent the weekend doing a lot of runs of the analysis in [coffea-casa-tutorials](https://github.com/CoffeaTeam/coffea-casa-tutorials/blob/master/analysis-casa.ipynb), and have come up with a list of warnings/errors I've had thrown my way during that time.

The warning was: 

`distributed.comm.tcp   - WARNING - Closing dangling stream in <TLS  local=tls://127.0.0.1:36762   remote=tls://localhost:8786>`

Where the number at the end tended to vary (I've seen 127.0.0.1:36762, 127.0.0.1:37072, and 127.0.0.1:46228, but I didn't think to record these the first few times the warning fired off). This sometimes occurred multiple times in a run, and sometimes did not occur at all. It doesn't seem to break anything (I think it's just a problem with a specific worker). This warning doesn't seem to have any correlation with min or max number of workers (I've seen it on 1-100, 40-300, and 100-300).

Additionally, I saw two different errors fire off once each, before pre-processing even began. When I re-ran the analysis, they went away. That's good in terms of it not being too serious, but bad in terms of trying to reproduce it...

`OSError:   Timed out trying to connect to 'tls://localhost:8786' after 10 s: Timed out   trying to connect to 'tls://localhost:8786' after 10 s: connect() didn't   finish in time`

`OSError:   Timed out trying to connect to 'tls://red-c0805.unl.edu:33073' after 10 s:   Timed out trying to connect to 'tls://red-c0805.unl.edu:33073' after 10 s: in   <distributed.comm.tcp.TLSConnector object at 0x7fb32ce6e3d0>: OSError:   [Errno 99] Cannot assign requested address`

The first happened with 40-200 workers, the second with 1-100.

If I get any more information, I'll post it here, but I think these are all issues with workers(?) and I'm not too sure how to poke around those.

**Comment by bbockelm** [comment] 2020-10-26 19:37
I think this is due to the blocking of the scheduler when interacting with HTCondor... @oshadura was tinkering with some ways to make this non-blocking.  Oksana, what's the latest on that work?

**Comment by oshadura** [comment] 2020-10-29 08:25
@bbockelm I have a branch where I tested if it is a problem making job submission fully in async way. The problem that I saw that the UI still freezes minimally, but while testing tutorial from @mat-adamec seems to be working (I couldn't reproduce the failure, but in fact, I never got a big number of workers).

**Comment by oshadura** [comment] 2020-11-13 14:50
Update: 

 - issue `distributed.comm.tcp - WARNING - Closing dangling stream in <TLS  local=tls://address:port  remote=tls://localhost:8786` is not connected with an issue about non-blocking I/O but discussed and actually never  been resolved in https://github.com/dask/distributed/issues/2507 I could try to take a look to see if it could be fixed.

- issue with ` OSError: Timed out trying to connect to 'tls://localhost:8786' after 10 s: Timed out trying to connect to 'tls://localhost:8786' after 10 s: connect() didn't finish in time ` or `OSError: Timed out trying to connect to 'tls://red-c0805.unl.edu:33073' after 10 s: Timed out trying to connect to 'tls://red-c0805.unl.edu:33073' after 10 s: in <distributed.comm.tcp.TLSConnector object at 0x7fb32ce6e3d0>: OSError: [Errno 99] Cannot assign requested address` with patch https://github.com/dask/dask-jobqueue/pull/473 is not appearing anymore, instead I see a lot of warnings with dangling streams:

```
[########                                ] | 20% Completed | 36.5s
distributed.comm.tcp - WARNING - Closing dangling stream in <TLS  local=tls://127.0.0.1:57082 remote=tls://localhost:8786>
distributed.comm.tcp - WARNING - Closing dangling stream in <TLS  local=tls://127.0.0.1:57080 remote=tls://localhost:8786>
distributed.comm.tcp - WARNING - Closing dangling stream in <TLS  local=tls://127.0.0.1:57084 remote=tls://localhost:8786>
distributed.comm.tcp - WARNING - Closing dangling stream in <TLS  local=tls://127.0.0.1:57086 remote=tls://localhost:8786>
[########################                ] | 61% Completed | 38.1s
distributed.comm.tcp - WARNING - Closing dangling stream in <TLS  local=tls://127.0.0.1:57090 remote=tls://localhost:8786>
[                                        ] | 0% Completed | 37.7s9s
distributed.comm.tcp - WARNING - Closing dangling stream in <TLS  local=tls://127.0.0.1:57322 remote=tls://localhost:8786>
distributed.comm.tcp - WARNING - Closing dangling stream in <TLS  local=tls://127.0.0.1:57320 remote=tls://localhost:8786>

[##                                      ] | 7% Completed |  1min 25.8s
````

- issue with UI freezing is still persist.

**Comment by oshadura** [comment] 2021-04-22 15:28
I think this is resolved :)

**Closed by oshadura** 2021-04-22 15:28 UTC
