### ISSUE TITLE
Dask errors periodically kill coffea-casa

### ISSUE THREAD

**Issue by mat-adamec** [CoffeaTeam/coffea-casa#308] opened 2022-07-04 18:32 UTC
I have reported this issue before in Slack, but it's still recurring whenever I spend extended periods of time in coffea-casa. At some point, a Dask Server Error will pop up:

![dask_server_error](https://user-images.githubusercontent.com/25493839/177204019-3aa47dd5-0ba3-4485-a7ff-3d5c8def0c20.png)

Which will require me to restart the server, otherwise I get spammed whenever I try to save a file with:

![file_save_error](https://user-images.githubusercontent.com/25493839/177204061-8f024b5c-5b96-4790-8131-da3eb6e91087.png)

But then it'll show up again after an hour or two of work. There doesn't seem to be any direct cause for this. Sometimes it pops up while I'm working, other times it pops up while I'm away but logged into the server in one of my tabs.

It would be great to get this fixed before July 14th so that it doesn't surface during the analysis talk then. If nobody else is encountering it, maybe I just need to get my secrets cleared? @oshadura

**Comment by mat-adamec** [comment] 2022-07-04 18:37
Sometimes I need to restart the server twice before the error disappears. In such a case, when I restart I get the popup again but when I click dismiss on it, I get another popup that says:

![server_unreachable](https://user-images.githubusercontent.com/25493839/177204624-84dfe7a4-0e0a-4470-bbb5-716c8f54ffbd.png)

Where the restart button leads to this page:

![server_unavailable](https://user-images.githubusercontent.com/25493839/177204636-a2845b61-526a-41d3-8d98-aee9e803eeed.png)

**Comment by oshadura** [comment] 2022-07-11 07:19
@mat-adamec is it happening on coffea.casa? or OD coffea-casa?

**Comment by mat-adamec** [comment] 2022-07-22 15:57
It's happening on both (and the flat-iron instance!)

**Comment by mat-adamec** [comment] 2022-08-14 18:05
This is still happening, but less urgent (until another talk comes up).

If others also run into this error, please comment so we can gather data about prevalence as I seem to be the only one who gets this so often.

**Comment by jthiltges** [comment] 2022-08-14 18:44
I'd made some recent changes to collect additional log output, which might be helpful. There was a notebook pod that ran for about an error, then failed:
```
Aug 14 12:00:31 c2415.shor.hcc.unl.edu conmon[3482082]: [I 2022-08-14 17:00:31.038 SingleUserLabApp mixins:614] Starting jupyterhub single-user server version 2.2.2
...
Aug 14 12:00:33 c2415.shor.hcc.unl.edu conmon[3482082]: [W 2022-08-14 17:00:33.852 SingleUserLabApp _version:68] jupyterhub version 1.3.0 != jupyterhub-singleuser version 2.2.2. This could cause failure to authenticate and result in redirect loops!
Aug 14 12:00:33 c2415.shor.hcc.unl.edu conmon[3482082]: [I 2022-08-14 17:00:33.852 SingleUserLabApp serverapp:2670] Serving notebooks from local directory: /home/cms-jovyan
Aug 14 12:00:33 c2415.shor.hcc.unl.edu conmon[3482082]: [I 2022-08-14 17:00:33.852 SingleUserLabApp serverapp:2670] Jupyter Server 1.16.0 is running at:
Aug 14 12:00:33 c2415.shor.hcc.unl.edu conmon[3482082]: [I 2022-08-14 17:00:33.852 SingleUserLabApp serverapp:2670] http://jupyter-matous-2eadamec-40cern-2ech:8888/user/matous.adamec@cern.ch/lab
...
Aug 14 13:00:47 c2415.shor.hcc.unl.edu conmon[3482082]: [C 2022-08-14 18:00:47.357 SingleUserLabApp serverapp:2120] received signal 15, stopping
Aug 14 13:00:47 c2415.shor.hcc.unl.edu conmon[3482082]: [I 2022-08-14 18:00:47.357 SingleUserLabApp serverapp:2459] Shutting down 9 extensions
Aug 14 13:00:47 c2415.shor.hcc.unl.edu conmon[3482082]: [I 2022-08-14 18:00:47.358 SingleUserLabApp serverapp:2433] Shutting down 2 kernels
Aug 14 13:00:47 c2415.shor.hcc.unl.edu conmon[3482082]: [I 2022-08-14 18:00:47.358 SingleUserLabApp multikernelmanager:258] Kernel shutdown: c0276316-0370-4b76-9dd3-5322cf689554
Aug 14 13:00:47 c2415.shor.hcc.unl.edu conmon[3482082]: [I 2022-08-14 18:00:47.358 SingleUserLabApp multikernelmanager:258] Kernel shutdown: af54dc6e-1801-4f26-97d3-3d6aa91bbaca
```

Searching for `serverapp:2120] received signal 15, stopping` pointed to a [dockerspawner issue](https://www.github.com/jupyterhub/dockerspawner/issues/452), where they identified a version mismatch between hub and notebook. And our logs show the same version issue: `jupyterhub version 1.3.0 != jupyterhub-singleuser version 2.2.2`.

I'm suspecting that might be the cause, or at least a next step to try.

**Comment by 7quantumphysics** [comment] 2022-10-07 03:28
Is there any progress on resolving this issue?  This same thing occurs for me as well.  I find that refreshing the page fixes the problem, but it is strange that I need to do this.  Especially when it occurs while running a dask job.

**Comment by oshadura** [comment] 2024-02-21 15:06
In the new environment, we have now recent jupyterhub version:
```
cms-jovyan@jupyter-oksana-2eshadura-40cern-2ech:~/PocketCoffea$ pip list | grep jupyterhub
jupyterhub                    3.1.1
```

**Closed by oshadura** 2024-02-21 15:06 UTC
Labels: bug, urgent
