### ISSUE TITLE
`uproot` version update to fix missing HTTP multipart header error

### ISSUE THREAD

**Issue by alexander-held** [CoffeaTeam/coffea-casa#326] opened 2022-08-29 15:56 UTC
When trying to read out all arrays from a remote file via `uproot`, the following fails:
```python
import uproot
uproot.open("https://xrootd-local.unl.edu:1094//store/user/AGC/datasets/RunIIFall15MiniAODv2/TT_TuneCUETP8M1_13TeV-powheg-pythia8/MINIAODSIM//PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext3-v1/00000/00DF0A73-17C2-E511-B086-E41D2D08DE30.root")["events"].arrays()
```
with a traceback of
```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/uproot/behaviors/TBranch.py", line 1125, in arrays
    _ranges_or_baskets_to_arrays(
  File "/opt/conda/lib/python3.8/site-packages/uproot/behaviors/TBranch.py", line 3502, in _ranges_or_baskets_to_arrays
    uproot.source.futures.delayed_raise(*obj)
  File "/opt/conda/lib/python3.8/site-packages/uproot/source/futures.py", line 36, in delayed_raise
    raise exception_value.with_traceback(traceback)
  File "/opt/conda/lib/python3.8/site-packages/uproot/behaviors/TBranch.py", line 3423, in chunk_to_basket
    basket = uproot.models.TBasket.Model_TBasket.read(
  File "/opt/conda/lib/python3.8/site-packages/uproot/model.py", line 805, in read
    self.read_members(chunk, cursor, context, file)
  File "/opt/conda/lib/python3.8/site-packages/uproot/models/TBasket.py", line 223, in read_members
    ) = cursor.fields(chunk, _tbasket_format1, context)
  File "/opt/conda/lib/python3.8/site-packages/uproot/source/cursor.py", line 197, in fields
    return format.unpack(chunk.get(start, stop, self, context))
  File "/opt/conda/lib/python3.8/site-packages/uproot/source/chunk.py", line 419, in get
    self.wait(insist=stop)
  File "/opt/conda/lib/python3.8/site-packages/uproot/source/chunk.py", line 356, in wait
    self._raw_data = numpy.frombuffer(self._future.result(), dtype=self._dtype)
  File "/opt/conda/lib/python3.8/site-packages/uproot/source/futures.py", line 116, in result
    delayed_raise(*self._excinfo)
  File "/opt/conda/lib/python3.8/site-packages/uproot/source/futures.py", line 36, in delayed_raise
    raise exception_value.with_traceback(traceback)
  File "/opt/conda/lib/python3.8/site-packages/uproot/source/http.py", line 338, in task
    resource.handle_multipart(source, futures, results, response)
  File "/opt/conda/lib/python3.8/site-packages/uproot/source/http.py", line 401, in handle_multipart
    raise OSError(
OSError: found 0 of 214 expected headers in HTTP multipart
for URL https://xrootd-local.unl.edu:1094//store/user/AGC/datasets/RunIIFall15MiniAODv2/TT_TuneCUETP8M1_13TeV-powheg-pythia8/MINIAODSIM//PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext3-v1/00000/00DF0A73-17C2-E511-B086-E41D2D08DE30.root
```
This is on the open data coffea-casa instance. Locally the command succeeds.

An update to the latest version of `uproot` (4.3.4) fixes this behavior.

**Comment by oshadura** [comment] 2024-02-21 14:30
```
cms-jovyan@jupyter-oksana-2eshadura-40cern-2ech:~/PocketCoffea$ python
Python 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:49:32) 
[GCC 12.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import uproot
>>> uproot.open("https://xrootd-local.unl.edu:1094//store/user/AGC/datasets/RunIIFall15MiniAODv2/TT_TuneCUETP8M1_13TeV-powheg-pythia8/MINIAODSIM//PU25nsData2015v1_76X_mcRun2_asymptotic_v12_ext3-v1/00000/00DF0A73-17C2-E511-B086-E41D2D08DE30.root")["events"].arrays()
<Array [{numberelectron: 1, ... ] type='41812 * {"numberelectron": int32, "nelec...'>
>>> 
```
looks like the issue is fixed in the new environment

**Closed by oshadura** 2024-02-21 14:30 UTC
